changelog:
  categories:
    - title: Breaking Changes
      labels:
        - "breaking change"
    - title: New features
      labels:
        - "enhancement"
    - title: Fixes
      labels:
        - "bug"
    - title: Documentation
      labels:
        - "documentation"
    - title: Code Quality
      labels:
        - "code quality"
    - title: Others
      labels: 
        - "*"
